#!/bin/bash

DATE=$(date +%Y%m%d)

fork(){
	sudo python ~/gitrepos/paperearth.net/django/mysite/manage.py runserver 0.0.0.0:80 &>~/logs/$DATE.log &
        child_pid=$!
        echo $child_pid > ~/gitrepos/paperearth.net/django.pid
}

if [ ! -f ~/gitrepos/paperearth.net/django.pid ]; then
	fork
else
	PID=`cat ~/gitrepos/paperearth.net/django.pid`
	if [[ ! `ps -p "$PID" --no-headers` ]]; then
		fork
	fi
fi

exit
